### PR TITLE
updated sample.env - added name to team

### PR DESCRIPTION
**Pull request by trevorjr31**
Just an initial PR as per CoDo.ai onboarding exercise
👍

### CODE REVIEW

**Comment by bonnieli** [comment]
Hi Trevor - looks like this branch includes both updating sample.env as described in this pull request but also include a lot of other changes. As hinted in your commit fcfd8e8, you're also including the homepage skeleton here. Did you intend to make a PR for the skeleton ticket or just a branching issue?

**Comment by trevorjr31** [comment]
Hi @bonnieli, 
Thank you for taking a look at this.

I did not create a new branch prior to starting work on the homepage. I reverted the change.

I was 3/4 of the way through building the home page on the weekend before realizing I don't even need it for  my Login/Signup ticket.. lol

I created a new branch for with that work before reverting it here, just in case some of it is needed in the future.

**Review by ezeilo-su — COMMENTED** [review]
LGTM! Thank you for adjusting the PR branch as noted by @bonnieli :+1:

**Review by rajivtitus — APPROVED** [review]
👍🏽

**Pull request merged**
